### ISSUE TITLE
expected scalar type Long but found Int

### ISSUE THREAD

**Issue by mpautzke** [celantur/panoptic_segm_demo#1]
Was trying to move to panoptic segmentation from semantic.  I can run this code using the semantic model, but when changing the base to panoptic, I receive "expected scalar type Long but found Int" when trying to train.  I've run the script to convert the semantic data into panoptic photos.  Using detectron2 3.0 (tag), pytorch 1.6.  Any ideas?

Traceback (most recent call last):
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\engine\train_loop.py", line 134, in train
    self.run_step()
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\engine\defaults.py", line 423, in run_step
    self._trainer.run_step()
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\engine\train_loop.py", line 228, in run_step
    loss_dict = self.model(data)
  File "C:\Users\mpautzke\Applications\Anaconda3\envs\detectron\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\modeling\meta_arch\panoptic_fpn.py", line 91, in forward
    sem_seg_results, sem_seg_losses = self.sem_seg_head(features, gt_sem_seg)
  File "C:\Users\mpautzke\Applications\Anaconda3\envs\detectron\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\modeling\meta_arch\semantic_seg.py", line 163, in forward
    return None, self.losses(x, targets)
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\modeling\meta_arch\semantic_seg.py", line 183, in losses
    loss = F.cross_entropy(
  File "C:\Users\mpautzke\Applications\Anaconda3\envs\detectron\lib\site-packages\torch\nn\functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "C:\Users\mpautzke\Applications\Anaconda3\envs\detectron\lib\site-packages\torch\nn\functional.py", line 2220, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: expected scalar type Long but found Int
[11/06 17:38:50 d2.engine.hooks]: Total training time: 0:00:06 (0:00:00 on hooks)
Traceback (most recent call last):
  File "C:/Users/mpautzke/Projects/ImageSegmentation/soilid_detectron/demo_pan.py", line 137, in <module>
    train(cfg)
  File "C:/Users/mpautzke/Projects/ImageSegmentation/soilid_detectron/demo_pan.py", line 110, in train
    trainer.train()
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\engine\defaults.py", line 413, in train
    super().train(self.start_iter, self.max_iter)
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\engine\train_loop.py", line 134, in train
    self.run_step()
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\engine\defaults.py", line 423, in run_step
    self._trainer.run_step()
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\engine\train_loop.py", line 228, in run_step
    loss_dict = self.model(data)
  File "C:\Users\mpautzke\Applications\Anaconda3\envs\detectron\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\modeling\meta_arch\panoptic_fpn.py", line 91, in forward
    sem_seg_results, sem_seg_losses = self.sem_seg_head(features, gt_sem_seg)
  File "C:\Users\mpautzke\Applications\Anaconda3\envs\detectron\lib\site-packages\torch\nn\modules\module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\modeling\meta_arch\semantic_seg.py", line 163, in forward
    return None, self.losses(x, targets)
  File "c:\users\mpautzke\projects\imagesegmentation\detectron2\detectron2\modeling\meta_arch\semantic_seg.py", line 183, in losses
    loss = F.cross_entropy(
  File "C:\Users\mpautzke\Applications\Anaconda3\envs\detectron\lib\site-packages\torch\nn\functional.py", line 2422, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "C:\Users\mpautzke\Applications\Anaconda3\envs\detectron\lib\site-packages\torch\nn\functional.py", line 2220, in nll_loss
    ret = torch._C._nn.nll_loss2d(input, target, weight, _Reduction.get_enum(reduction), ignore_index)
RuntimeError: expected scalar type Long but found Int

**Comment by HagaiRaja** [comment]
Hi @mpautzke did you solve the issue? I also got the same error

**Comment by 7ENG1Z** [comment]
Hi, did you solve the problem?
